[tool.poetry]
name = "mindly-backend"
version = "0.1.0"
description = "Mindly - Rede Social MVP (Backend)"
authors = ["Cristiano <cristiano.tobias@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
django = "^5.1"
djangorestframework = "^3.15"
psycopg2-binary = "^2.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"